.

diff --git a/ci-helpers.v2.yml b/ci-helpers.v2.yml
--- a/ci-helpers.v2.yml
+++ b/ci-helpers.v2.yml
@@ -93,11 +93,11 @@
   tags:
     - $RUNNER
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+") && $DEPLOY_IKEA == "true"'
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+") && $DEPLOY_IKEA == "true" && $GITLAB_USER_LOGIN =~ $AUTHORIZED_USERS'
       variables:
         environment: "production"
         PROJECT: ikea
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+") && $DEPLOY_VERILA == "true"'
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ ".+\/hotfix\/.+") && $DEPLOY_VERILA == "true" $GITLAB_USER_LOGIN =~ $AUTHORIZED_USERS'
       variables:
         environment: "production"
         PROJECT: verila
@@ -167,16 +167,21 @@
     name: $environment
   script: 
     - |
-      PROJ_PREFIX="${PROJECT:0:2}"; PROJ_PREFIX="${PROJ_PREFIX^^}"
-      LAST_TAG=$(git tag -l "*-$PROJ_PREFIX" | sort -V | tail -1)
-      IFS='-.' read -r -a tag_components <<< "$LAST_TAG"
-      MAJOR=${tag_components[0]}
-      MINOR=${tag_components[1]}
-      PATCH=${tag_components[2]}
-      PATCH=$((PATCH + 1))
-      TAG="$MAJOR.$MINOR.$PATCH-$PROJ_PREFIX"
-      echo "The created tag is "$TAG""
-      echo "TAG=$TAG" >> cache.env
+      if [[ "$environment" == "production" && $GITLAB_USER_LOGIN =~ $AUTHORIZED_USERS ]]; then
+        echo "You can't do that"
+        exit 1
+      else:
+        PROJ_PREFIX="${PROJECT:0:2}"; PROJ_PREFIX="${PROJ_PREFIX^^}"
+        LAST_TAG=$(git tag -l "*-$PROJ_PREFIX" | sort -V | tail -1)
+        IFS='-.' read -r -a tag_components <<< "$LAST_TAG"
+        MAJOR=${tag_components[0]}
+        MINOR=${tag_components[1]}
+        PATCH=${tag_components[2]}
+        PATCH=$((PATCH + 1))
+        TAG="$MAJOR.$MINOR.$PATCH-$PROJ_PREFIX"
+        echo "The created tag is "$TAG""
+        echo "TAG=$TAG" >> cache.env
+      fi
   rules:
     - if: '$CI_PIPELINE_SOURCE == "schedule" && $HOTFIX_DEPLOYMENT == "true"'
   artifacts:
